const TEAM_META = {
  Germany: { shortName: "德国", flag: "🇩🇪" },
  Spain: { shortName: "西班牙", flag: "🇪🇸" },
  England: { shortName: "英格兰", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  France: { shortName: "法国", flag: "🇫🇷" },
  Brazil: { shortName: "巴西", flag: "🇧🇷" },
  Argentina: { shortName: "阿根廷", flag: "🇦🇷" },
  Japan: { shortName: "日本", flag: "🇯🇵" },
  "United States": { shortName: "美国", flag: "🇺🇸" },
  USA: { shortName: "美国", flag: "🇺🇸" },
  Mexico: { shortName: "墨西哥", flag: "🇲🇽" },
  "South Africa": { shortName: "南非", flag: "🇿🇦" },
  Croatia: { shortName: "克罗地亚", flag: "🇭🇷" },
  Senegal: { shortName: "塞内加尔", flag: "🇸🇳" },
  Portugal: { shortName: "葡萄牙", flag: "🇵🇹" },
  Uruguay: { shortName: "乌拉圭", flag: "🇺🇾" },
  Netherlands: { shortName: "荷兰", flag: "🇳🇱" },
  Colombia: { shortName: "哥伦比亚", flag: "🇨🇴" },
  Ecuador: { shortName: "厄瓜多尔", flag: "🇪🇨" },
  Norway: { shortName: "挪威", flag: "🇳🇴" },
  Turkey: { shortName: "土耳其", flag: "🇹🇷" },
  Belgium: { shortName: "比利时", flag: "🇧🇪" },
  Australia: { shortName: "澳大利亚", flag: "🇦🇺" },
  Algeria: { shortName: "阿尔及利亚", flag: "🇩🇿" },
  Austria: { shortName: "奥地利", flag: "🇦🇹" },
  Jordan: { shortName: "约旦", flag: "🇯🇴" },
  Uzbekistan: { shortName: "乌兹别克斯坦", flag: "🇺🇿" },
  Iran: { shortName: "伊朗", flag: "🇮🇷" },
  Tunisia: { shortName: "突尼斯", flag: "🇹🇳" },
  "Cape Verde Islands": { shortName: "佛得角", flag: "🇨🇻" },
  "Cape Verde": { shortName: "佛得角", flag: "🇨🇻" },
  "New Zealand": { shortName: "新西兰", flag: "🇳🇿" },
  Ghana: { shortName: "加纳", flag: "🇬🇭" },
  Egypt: { shortName: "埃及", flag: "🇪🇬" },
  "Saudi Arabia": { shortName: "沙特阿拉伯", flag: "🇸🇦" },
  Bolivia: { shortName: "玻利维亚", flag: "🇧🇴" },
  Suriname: { shortName: "苏里南", flag: "🇸🇷" },
  Iraq: { shortName: "伊拉克", flag: "🇮🇶" },
  "New Caledonia": { shortName: "新喀里多尼亚", flag: "🇳🇨" },
  "DR Congo": { shortName: "刚果（金）", flag: "🇨🇩" },
  Kosovo: { shortName: "科索沃", flag: "🇽🇰" },
  Romania: { shortName: "罗马尼亚", flag: "🇷🇴" },
  Slovakia: { shortName: "斯洛伐克", flag: "🇸🇰" },
  Albania: { shortName: "阿尔巴尼亚", flag: "🇦🇱" },
  Sweden: { shortName: "瑞典", flag: "🇸🇪" },
  Ukraine: { shortName: "乌克兰", flag: "🇺🇦" },
  "Czechia": { shortName: "捷克", flag: "🇨🇿" },
  "Ivory Coast": { shortName: "科特迪瓦", flag: "🇨🇮" },
  "Côte d'Ivoire": { shortName: "科特迪瓦", flag: "🇨🇮" },
  Curacao: { shortName: "库拉索", flag: "🇨🇼" },
  "Curaçao": { shortName: "库拉索", flag: "🇨🇼" },
  Jamaica: { shortName: "牙买加", flag: "🇯🇲" },
  Panama: { shortName: "巴拿马", flag: "🇵🇦" },
  Serbia: { shortName: "塞尔维亚", flag: "🇷🇸" },
  "Costa Rica": { shortName: "哥斯达黎加", flag: "🇨🇷" },
  Canada: { shortName: "加拿大", flag: "🇨🇦" },
  Paraguay: { shortName: "巴拉圭", flag: "🇵🇾" },
  Qatar: { shortName: "卡塔尔", flag: "🇶🇦" },
  Switzerland: { shortName: "瑞士", flag: "🇨🇭" },
  Morocco: { shortName: "摩洛哥", flag: "🇲🇦" },
  Scotland: { shortName: "苏格兰", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  Haiti: { shortName: "海地", flag: "🇭🇹" },
  "Korea Republic": { shortName: "韩国", flag: "🇰🇷" },
  Denmark: { shortName: "丹麦", flag: "🇩🇰" },
  "North Macedonia": { shortName: "北马其顿", flag: "🇲🇰" },
  "Czech Republic": { shortName: "捷克", flag: "🇨🇿" },
  Ireland: { shortName: "爱尔兰", flag: "🇮🇪" },
  Italy: { shortName: "意大利", flag: "🇮🇹" },
  "Northern Ireland": { shortName: "北爱尔兰", flag: "🇬🇧" },
  Wales: { shortName: "威尔士", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
  "Bosnia and Herzegovina": { shortName: "波黑", flag: "🇧🇦" },
  "South Korea": { shortName: "韩国", flag: "🇰🇷" },
  "West Germany": { shortName: "西德", flag: "🇩🇪" },
  "Soviet Union": { shortName: "苏联", flag: "🇷🇺" },
  USSR: { shortName: "苏联", flag: "🇷🇺" },
  Yugoslavia: { shortName: "南斯拉夫", flag: "🇷🇸" },
  Czechoslovakia: { shortName: "捷克斯洛伐克", flag: "🇨🇿" },
  Russia: { shortName: "俄罗斯", flag: "🇷🇺" },
  Poland: { shortName: "波兰", flag: "🇵🇱" },
  Peru: { shortName: "秘鲁", flag: "🇵🇪" },
  Chile: { shortName: "智利", flag: "🇨🇱" },
  Cameroon: { shortName: "喀麦隆", flag: "🇨🇲" },
  Nigeria: { shortName: "尼日利亚", flag: "🇳🇬" },
  Greece: { shortName: "希腊", flag: "🇬🇷" },
  Slovenia: { shortName: "斯洛文尼亚", flag: "🇸🇮" },
  Honduras: { shortName: "洪都拉斯", flag: "🇭🇳" },
  Hungary: { shortName: "匈牙利", flag: "🇭🇺" },
  Venezuela: { shortName: "委内瑞拉", flag: "🇻🇪" },
  Cuba: { shortName: "古巴", flag: "🇨🇺" },
  "Trinidad and Tobago": { shortName: "特多", flag: "🇹🇹" },
  "Trinidad & Tobago": { shortName: "特多", flag: "🇹🇹" },
  Iceland: { shortName: "冰岛", flag: "🇮🇸" },
  Finland: { shortName: "芬兰", flag: "🇫🇮" },
  "China PR": { shortName: "中国", flag: "🇨🇳" },
  China: { shortName: "中国", flag: "🇨🇳" },
  Oman: { shortName: "阿曼", flag: "🇴🇲" },
  "United Arab Emirates": { shortName: "阿联酋", flag: "🇦🇪" },
  UAE: { shortName: "阿联酋", flag: "🇦🇪" },
  Bahrain: { shortName: "巴林", flag: "🇧🇭" },
  Kuwait: { shortName: "科威特", flag: "🇰🇼" },
  "Chinese Taipei": { shortName: "中华台北", flag: "🇹🇼" },
  Mali: { shortName: "马里", flag: "🇲🇱" },
  Guinea: { shortName: "几内亚", flag: "🇬🇳" },
  Comoros: { shortName: "科摩罗", flag: "🇰🇲" },
  Zambia: { shortName: "赞比亚", flag: "🇿🇲" },
  Angola: { shortName: "安哥拉", flag: "🇦🇴" },
  Kenya: { shortName: "肯尼亚", flag: "🇰🇪" },
  Tanzania: { shortName: "坦桑尼亚", flag: "🇹🇿" },
  Zimbabwe: { shortName: "津巴布韦", flag: "🇿🇼" },
  Mozambique: { shortName: "莫桑比克", flag: "🇲🇿" },
  Ethiopia: { shortName: "埃塞俄比亚", flag: "🇪🇹" },
  Uganda: { shortName: "乌干达", flag: "🇺🇬" },
  Libya: { shortName: "利比亚", flag: "🇱🇾" },
  Sudan: { shortName: "苏丹", flag: "🇸🇩" },
  Madagascar: { shortName: "马达加斯加", flag: "🇲🇬" },
  Benin: { shortName: "贝宁", flag: "🇧🇯" },
  Gabon: { shortName: "加蓬", flag: "🇬🇦" },
  Congo: { shortName: "刚果（布）", flag: "🇨🇬" },
  "Burkina Faso": { shortName: "布基纳法索", flag: "🇧🇫" },
  Niger: { shortName: "尼日尔", flag: "🇳🇪" },
  Mauritania: { shortName: "毛里塔尼亚", flag: "🇲🇷" },
  "Central African Republic": { shortName: "中非", flag: "🇨🇫" },
  Lebanon: { shortName: "黎巴嫩", flag: "🇱🇧" },
  Syria: { shortName: "叙利亚", flag: "🇸🇾" },
  Palestine: { shortName: "巴勒斯坦", flag: "🇵🇸" },
  Kyrgyzstan: { shortName: "吉尔吉斯斯坦", flag: "🇰🇬" },
  Tajikistan: { shortName: "塔吉克斯坦", flag: "🇹🇯" },
  Turkmenistan: { shortName: "土库曼斯坦", flag: "🇹🇲" },
  Kazakhstan: { shortName: "哈萨克斯坦", flag: "🇰🇿" },
  Azerbaijan: { shortName: "阿塞拜疆", flag: "🇦🇿" },
  Armenia: { shortName: "亚美尼亚", flag: "🇦🇲" },
  Georgia: { shortName: "格鲁吉亚", flag: "🇬🇪" },
  Belarus: { shortName: "白俄罗斯", flag: "🇧🇾" },
  Bulgaria: { shortName: "保加利亚", flag: "🇧🇬" },
  Montenegro: { shortName: "黑山", flag: "🇲🇪" },
  Lithuania: { shortName: "立陶宛", flag: "🇱🇹" },
  Latvia: { shortName: "拉脱维亚", flag: "🇱🇻" },
  Estonia: { shortName: "爱沙尼亚", flag: "🇪🇪" },
  Luxembourg: { shortName: "卢森堡", flag: "🇱🇺" },
  "Faroe Islands": { shortName: "法罗群岛", flag: "🇫🇴" },
  Malta: { shortName: "马耳他", flag: "🇲🇹" },
  Cyprus: { shortName: "塞浦路斯", flag: "🇨🇾" },
  "El Salvador": { shortName: "萨尔瓦多", flag: "🇸🇻" },
  Guatemala: { shortName: "危地马拉", flag: "🇬🇹" },
  Nicaragua: { shortName: "尼加拉瓜", flag: "🇳🇮" },
  Belize: { shortName: "伯利兹", flag: "🇧🇿" },
  Barbados: { shortName: "巴巴多斯", flag: "🇧🇧" },
  Guyana: { shortName: "圭亚那", flag: "🇬🇾" },
  "Dominican Republic": { shortName: "多米尼加共和国", flag: "🇩🇴" },
  Thailand: { shortName: "泰国", flag: "🇹🇭" },
  Vietnam: { shortName: "越南", flag: "🇻🇳" },
  Indonesia: { shortName: "印度尼西亚", flag: "🇮🇩" },
  Philippines: { shortName: "菲律宾", flag: "🇵🇭" },
  Malaysia: { shortName: "马来西亚", flag: "🇲🇾" },
  Myanmar: { shortName: "缅甸", flag: "🇲🇲" },
  India: { shortName: "印度", flag: "🇮🇳" },
  Bangladesh: { shortName: "孟加拉国", flag: "🇧🇩" },
  Nepal: { shortName: "尼泊尔", flag: "🇳🇵" },
  Afghanistan: { shortName: "阿富汗", flag: "🇦🇫" },
  Pakistan: { shortName: "巴基斯坦", flag: "🇵🇰" },
  "Korea DPR": { shortName: "朝鲜", flag: "🇰🇵" },
  Mongolia: { shortName: "蒙古", flag: "🇲🇳" },
  Tahiti: { shortName: "塔希提", flag: "🇵🇫" },
  Fiji: { shortName: "斐济", flag: "🇫🇯" },
  "Papua New Guinea": { shortName: "巴布亚新几内亚", flag: "🇵🇬" },
  "Solomon Islands": { shortName: "所罗门群岛", flag: "🇸🇧" },
  Vanuatu: { shortName: "瓦努阿图", flag: "🇻🇺" },
  "Den/Mkd/Cze/Irl": { shortName: "丹/北马/捷/爱", flag: "🏳️" },
  "Ita/Nir/Wal/BiH": { shortName: "意/北爱/威/波黑", flag: "🏳️" },
  "Tur/Rou/Svk/Kos": { shortName: "土/罗/斯/科", flag: "🏳️" },
  "Ukr/Swe/Pol/Alb": { shortName: "乌/瑞/波/阿", flag: "🏳️" },
  "Bol/Sur/Irq": { shortName: "玻/苏/伊", flag: "🏳️" },
  "Ncl/Jam/Cod": { shortName: "新喀/牙/刚果金", flag: "🏳️" },
  MexicoCity: { shortName: "墨西哥城" },
  "Los Angeles": { shortName: "洛杉矶" },
  "New York": { shortName: "纽约" },
  Seattle: { shortName: "西雅图" },
  Dallas: { shortName: "达拉斯" },
  Toronto: { shortName: "多伦多" },
  Culiacan: { shortName: "库利阿坎" },
  "Culiacán": { shortName: "库利阿坎" },
  Zapopan: { shortName: "萨波潘" },
  "Santa Clara": { shortName: "圣克拉拉" },
  "East Rutherford": { shortName: "东拉瑟福德" },
  "SoFi Stadium": { shortName: "洛杉矶" },
  "MetLife Stadium": { shortName: "纽约" },
  "BC Place": { shortName: "温哥华" },
  Vancouver: { shortName: "温哥华" },
  Atlanta: { shortName: "亚特兰大" },
  Houston: { shortName: "休斯敦" },
  Miami: { shortName: "迈阿密" },
  Boston: { shortName: "波士顿" },
  Philadelphia: { shortName: "费城" },
  Monterrey: { shortName: "蒙特雷" },
  Guadalajara: { shortName: "瓜达拉哈拉" },
  KansasCity: { shortName: "堪萨斯城" },
  // Polymarket playoff placeholder names
  "CZE/DEN/MKD/IRL": { shortName: "捷/丹/北马/爱", flag: "🏳️" },
  "BIH/ITA/NIR/WAL": { shortName: "波黑/意/北爱/威", flag: "🏳️" },
  "KOS/ROU/SVK/TUR": { shortName: "科索沃/罗/斯洛伐克/土", flag: "🏳️" },
  // SportMonks locale=zh variants that differ from our shortNames
  "韩国队": { shortName: "韩国", flag: "🇰🇷" },
  "丹麦/北马其顿/捷克/爱尔兰": { shortName: "丹/北马/捷/爱", flag: "🏳️" },
  "意大利/北爱尔兰/威尔士/波斯尼亚与黑塞哥维那": { shortName: "意/北爱/威/波黑", flag: "🏳️" },
  "土耳其/罗马尼亚/斯洛伐克/科索沃": { shortName: "土/罗/斯/科", flag: "🏳️" },
  "乌克兰/瑞典/波兰/阿尔巴尼亚": { shortName: "乌/瑞/波/阿", flag: "🏳️" },
  "玻利维亚/苏里南/伊拉克": { shortName: "玻/苏/伊", flag: "🏳️" },
  "新喀里多尼亚/牙买加/刚果民主共和国": { shortName: "新喀/牙/刚果金", flag: "🏳️" },
};

// Reverse map: Chinese shortName → meta (for locale=zh API responses)
const ZH_REVERSE = {};
// Reverse map: Chinese shortName → English name (for team-strengths matching)
const ZH_TO_EN = {};
for (const [enName, meta] of Object.entries(TEAM_META)) {
  if (meta.shortName && meta.flag) {
    ZH_REVERSE[meta.shortName] = meta;
    ZH_TO_EN[meta.shortName] = enName;
  }
}

export function getTeamMeta(name) {
  return TEAM_META[name] || ZH_REVERSE[name] || { shortName: name, flag: "🏳️" };
}

export function getTeamLabel(name) {
  return getTeamMeta(name).shortName;
}

export function normalizeTeamDisplay(team) {
  const meta = getTeamMeta(team?.originalName || team?.name || "");
  return {
    ...team,
    name: meta.shortName || team?.name || "",
    flag: team?.flag && team.flag !== "🏳️" ? team.flag : meta.flag,
  };
}

export function getCityLabel(name) {
  return TEAM_META[name]?.shortName || name || "";
}

/**
 * Convert a team name (possibly Chinese) to its English name.
 * Returns the input unchanged if no mapping exists.
 */
export function toEnglishName(name) {
  if (!name) return name;
  // Already English (exists in TEAM_META)
  if (TEAM_META[name]) return name;
  // Chinese → English
  return ZH_TO_EN[name] || name;
}
