const TEAM_META = {
  Germany: { shortName: "德国", flag: "🇩🇪" },
  Spain: { shortName: "西班牙", flag: "🇪🇸" },
  England: { shortName: "英格兰", flag: "🏴" },
  France: { shortName: "法国", flag: "🇫🇷" },
  Brazil: { shortName: "巴西", flag: "🇧🇷" },
  Argentina: { shortName: "阿根廷", flag: "🇦🇷" },
  Japan: { shortName: "日本", flag: "🇯🇵" },
  "United States": { shortName: "美国", flag: "🇺🇸" },
  USA: { shortName: "美国", flag: "🇺🇸" },
  Mexico: { shortName: "墨西哥", flag: "🇲🇽" },
  "South Africa": { shortName: "南非", flag: "🇿🇦" },
  Croatia: { shortName: "克罗地亚", flag: "🇭🇷" },
  Senegal: { shortName: "塞内加尔", flag: "🇸🇳" },
  Portugal: { shortName: "葡萄牙", flag: "🇵🇹" },
  Uruguay: { shortName: "乌拉圭", flag: "🇺🇾" },
  Netherlands: { shortName: "荷兰", flag: "🇳🇱" },
  Colombia: { shortName: "哥伦比亚", flag: "🇨🇴" },
  Ecuador: { shortName: "厄瓜多尔", flag: "🇪🇨" },
  Norway: { shortName: "挪威", flag: "🇳🇴" },
  Turkey: { shortName: "土耳其", flag: "🇹🇷" },
  Belgium: { shortName: "比利时", flag: "🇧🇪" },
  Australia: { shortName: "澳大利亚", flag: "🇦🇺" },
  Algeria: { shortName: "阿尔及利亚", flag: "🇩🇿" },
  Austria: { shortName: "奥地利", flag: "🇦🇹" },
  Jordan: { shortName: "约旦", flag: "🇯🇴" },
  Uzbekistan: { shortName: "乌兹别克斯坦", flag: "🇺🇿" },
  Iran: { shortName: "伊朗", flag: "🇮🇷" },
  Tunisia: { shortName: "突尼斯", flag: "🇹🇳" },
  "Cape Verde Islands": { shortName: "佛得角", flag: "🇨🇻" },
  "Cape Verde": { shortName: "佛得角", flag: "🇨🇻" },
  "New Zealand": { shortName: "新西兰", flag: "🇳🇿" },
  Ghana: { shortName: "加纳", flag: "🇬🇭" },
  Egypt: { shortName: "埃及", flag: "🇪🇬" },
  "Saudi Arabia": { shortName: "沙特阿拉伯", flag: "🇸🇦" },
  Bolivia: { shortName: "玻利维亚", flag: "🇧🇴" },
  Suriname: { shortName: "苏里南", flag: "🇸🇷" },
  Iraq: { shortName: "伊拉克", flag: "🇮🇶" },
  "New Caledonia": { shortName: "新喀里多尼亚", flag: "🇳🇨" },
  "DR Congo": { shortName: "刚果（金）", flag: "🇨🇩" },
  Kosovo: { shortName: "科索沃", flag: "🇽🇰" },
  Romania: { shortName: "罗马尼亚", flag: "🇷🇴" },
  Slovakia: { shortName: "斯洛伐克", flag: "🇸🇰" },
  Albania: { shortName: "阿尔巴尼亚", flag: "🇦🇱" },
  Sweden: { shortName: "瑞典", flag: "🇸🇪" },
  Ukraine: { shortName: "乌克兰", flag: "🇺🇦" },
  "Czechia": { shortName: "捷克", flag: "🇨🇿" },
  "Ivory Coast": { shortName: "科特迪瓦", flag: "🇨🇮" },
  "Côte d'Ivoire": { shortName: "科特迪瓦", flag: "🇨🇮" },
  Curacao: { shortName: "库拉索", flag: "🇨🇼" },
  "Curaçao": { shortName: "库拉索", flag: "🇨🇼" },
  Jamaica: { shortName: "牙买加", flag: "🇯🇲" },
  Panama: { shortName: "巴拿马", flag: "🇵🇦" },
  Serbia: { shortName: "塞尔维亚", flag: "🇷🇸" },
  "Costa Rica": { shortName: "哥斯达黎加", flag: "🇨🇷" },
  Canada: { shortName: "加拿大", flag: "🇨🇦" },
  Paraguay: { shortName: "巴拉圭", flag: "🇵🇾" },
  Qatar: { shortName: "卡塔尔", flag: "🇶🇦" },
  Switzerland: { shortName: "瑞士", flag: "🇨🇭" },
  Morocco: { shortName: "摩洛哥", flag: "🇲🇦" },
  Scotland: { shortName: "苏格兰", flag: "🏴" },
  Haiti: { shortName: "海地", flag: "🇭🇹" },
  "Korea Republic": { shortName: "韩国", flag: "🇰🇷" },
  Denmark: { shortName: "丹麦", flag: "🇩🇰" },
  "North Macedonia": { shortName: "北马其顿", flag: "🇲🇰" },
  "Czech Republic": { shortName: "捷克", flag: "🇨🇿" },
  Ireland: { shortName: "爱尔兰", flag: "🇮🇪" },
  Italy: { shortName: "意大利", flag: "🇮🇹" },
  "Northern Ireland": { shortName: "北爱尔兰", flag: "🇬🇧" },
  Wales: { shortName: "威尔士", flag: "🏴" },
  "Bosnia and Herzegovina": { shortName: "波黑", flag: "🇧🇦" },
  "South Korea": { shortName: "韩国", flag: "🇰🇷" },
  "West Germany": { shortName: "西德", flag: "🇩🇪" },
  "Soviet Union": { shortName: "苏联", flag: "🇷🇺" },
  USSR: { shortName: "苏联", flag: "🇷🇺" },
  Yugoslavia: { shortName: "南斯拉夫", flag: "🇷🇸" },
  Czechoslovakia: { shortName: "捷克斯洛伐克", flag: "🇨🇿" },
  Russia: { shortName: "俄罗斯", flag: "🇷🇺" },
  Poland: { shortName: "波兰", flag: "🇵🇱" },
  Peru: { shortName: "秘鲁", flag: "🇵🇪" },
  Chile: { shortName: "智利", flag: "🇨🇱" },
  Cameroon: { shortName: "喀麦隆", flag: "🇨🇲" },
  Nigeria: { shortName: "尼日利亚", flag: "🇳🇬" },
  Greece: { shortName: "希腊", flag: "🇬🇷" },
  Slovenia: { shortName: "斯洛文尼亚", flag: "🇸🇮" },
  Honduras: { shortName: "洪都拉斯", flag: "🇭🇳" },
  "Den/Mkd/Cze/Irl": { shortName: "丹/北马/捷/爱", flag: "🏳️" },
  "Ita/Nir/Wal/BiH": { shortName: "意/北爱/威/波黑", flag: "🏳️" },
  "Tur/Rou/Svk/Kos": { shortName: "土/罗/斯/科", flag: "🏳️" },
  "Ukr/Swe/Pol/Alb": { shortName: "乌/瑞/波/阿", flag: "🏳️" },
  "Bol/Sur/Irq": { shortName: "玻/苏/伊", flag: "🏳️" },
  "Ncl/Jam/Cod": { shortName: "新喀/牙/刚果金", flag: "🏳️" },
  MexicoCity: { shortName: "墨西哥城" },
  "Los Angeles": { shortName: "洛杉矶" },
  "New York": { shortName: "纽约" },
  Seattle: { shortName: "西雅图" },
  Dallas: { shortName: "达拉斯" },
  Toronto: { shortName: "多伦多" },
  Culiacan: { shortName: "库利阿坎" },
  "Culiacán": { shortName: "库利阿坎" },
  Zapopan: { shortName: "萨波潘" },
  "Santa Clara": { shortName: "圣克拉拉" },
  "East Rutherford": { shortName: "东拉瑟福德" },
  "SoFi Stadium": { shortName: "洛杉矶" },
  "MetLife Stadium": { shortName: "纽约" },
  "BC Place": { shortName: "温哥华" },
  Vancouver: { shortName: "温哥华" },
  Atlanta: { shortName: "亚特兰大" },
  Houston: { shortName: "休斯敦" },
  Miami: { shortName: "迈阿密" },
  Boston: { shortName: "波士顿" },
  Philadelphia: { shortName: "费城" },
  Monterrey: { shortName: "蒙特雷" },
  Guadalajara: { shortName: "瓜达拉哈拉" },
  KansasCity: { shortName: "堪萨斯城" },
};

export function getTeamMeta(name) {
  return TEAM_META[name] || { shortName: name, flag: "🏳️" };
}

export function getTeamLabel(name) {
  return getTeamMeta(name).shortName;
}

export function normalizeTeamDisplay(team) {
  const meta = getTeamMeta(team?.originalName || team?.name || "");
  return {
    ...team,
    name: meta.shortName || team?.name || "",
    flag: team?.flag && team.flag !== "🏳️" ? team.flag : meta.flag,
  };
}

export function getCityLabel(name) {
  return TEAM_META[name]?.shortName || name || "";
}
