// Polymarket 英文名 → 中文名 映射表（用于将 Polymarket 数据与 ELO 模型匹配）
export const EN_TO_ZH = {
  "Spain": "西班牙",
  "France": "法国",
  "England": "英格兰",
  "Brazil": "巴西",
  "Argentina": "阿根廷",
  "Germany": "德国",
  "Portugal": "葡萄牙",
  "Netherlands": "荷兰",
  "Belgium": "比利时",
  "Italy": "意大利",
  "Morocco": "摩洛哥",
  "Uruguay": "乌拉圭",
  "United States": "美国",
  "USA": "美国",
  "Mexico": "墨西哥",
  "Colombia": "哥伦比亚",
  "Croatia": "克罗地亚",
  "Denmark": "丹麦",
  "Switzerland": "瑞士",
  "Senegal": "塞内加尔",
  "Japan": "日本",
  "South Korea": "韩国",
  "Korea Republic": "韩国",
  "Australia": "澳大利亚",
  "Canada": "加拿大",
  "Chile": "智利",
  "Ecuador": "厄瓜多尔",
  "Peru": "秘鲁",
  "Turkey": "土耳其",
  "Türkiye": "土耳其",
  "Poland": "波兰",
  "Serbia": "塞尔维亚",
  "Ukraine": "乌克兰",
  "Austria": "奥地利",
  "Hungary": "匈牙利",
  "Czech Republic": "捷克",
  "Romania": "罗马尼亚",
  "Sweden": "瑞典",
  "Norway": "挪威",
  "Saudi Arabia": "沙特阿拉伯",
  "Iran": "伊朗",
  "Nigeria": "尼日利亚",
  "Cameroon": "喀麦隆",
  "Ivory Coast": "科特迪瓦",
  "Côte d'Ivoire": "科特迪瓦",
  "Ghana": "加纳",
  "Egypt": "埃及",
  "Algeria": "阿尔及利亚",
  "Tunisia": "突尼斯",
  "New Zealand": "新西兰",
  "Costa Rica": "哥斯达黎加",
  "Panama": "巴拿马",
  "Jamaica": "牙买加",
  "Honduras": "洪都拉斯",
  "Venezuela": "委内瑞拉",
  "Paraguay": "巴拉圭",
  "Bolivia": "玻利维亚",
  "Qatar": "卡塔尔",
  "South Africa": "南非",
  "Mali": "马里",
  "Burkina Faso": "布基纳法索",
  "Zambia": "赞比亚",
  "China": "中国",
  "China PR": "中国",
  "Iraq": "伊拉克",
  "Jordan": "约旦",
  "UAE": "阿联酋",
  "United Arab Emirates": "阿联酋",
  "Scotland": "苏格兰",
  "Wales": "威尔士",
  "Albania": "阿尔巴尼亚",
  "Slovakia": "斯洛伐克",
  "Slovenia": "斯洛文尼亚",
  "Greece": "希腊",
  "Iceland": "冰岛",
  "Ireland": "爱尔兰",
  "Georgia": "格鲁吉亚",
  "Uzbekistan": "乌兹别克斯坦",
  "El Salvador": "萨尔瓦多",
  "Guatemala": "危地马拉",
  "Haiti": "海地",
};
