#!/usr/bin/env python3
"""Translate coach/manager names to Chinese using GPT."""
import json, glob, re, urllib.request, os
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")

def main():
    if not OPENAI_API_KEY:
        print("ERROR: OPENAI_API_KEY not set")
        return

    # Collect manager names
    managers = set()
    for f in sorted(glob.glob(str(PROJECT / "public/data/team-detail/*.json"))):
        with open(f) as fh:
            data = json.load(fh)
        for t in data.get("tournaments", []):
            m = t.get("manager", "")
            if m:
                managers.add(m)

    # Load existing
    existing = {}
    js_path = PROJECT / "lib/player-names-zh.js"
    with open(js_path) as fh:
        for line in fh:
            m2 = re.match(r'\s*"([^"]+)":\s*"([^"]+)"', line)
            if m2:
                existing[m2.group(1)] = m2.group(2)

    missing = sorted([m for m in managers if m not in existing])
    print(f"Missing coaches: {len(missing)}")

    if not missing:
        print("Nothing to do!")
        return

    # Translate in batches
    BATCH = 80
    new_trans = {}
    total_b = (len(missing) + BATCH - 1) // BATCH

    for i in range(0, len(missing), BATCH):
        batch = missing[i:i + BATCH]
        bn = i // BATCH + 1
        print(f"  Batch {bn}/{total_b} ({len(batch)} names)...")

        names_text = "\n".join(batch)
        prompt = f"""你是一名资深足球翻译编辑。请将以下足球教练/主帅的英文名翻译为中文。

要求：
1. 使用中国体育媒体最常用的译名
2. 知名教练用公认简称（如 Ferguson → 弗格森，Guardiola → 瓜迪奥拉）
3. 只输出 JSON 对象，key 是英文名，value 是中文名
4. 不要 markdown 代码块

教练名单：
{names_text}"""

        payload = json.dumps({
            "model": "gpt-4o-mini",
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": 4000,
            "temperature": 0.1,
        })

        req = urllib.request.Request(
            "https://api.openai.com/v1/chat/completions",
            data=payload.encode("utf-8"),
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {OPENAI_API_KEY}",
            },
        )

        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                result = json.loads(resp.read().decode("utf-8"))
            usage = result.get("usage", {})
            cost = (usage.get("prompt_tokens", 0) * 0.15 + usage.get("completion_tokens", 0) * 0.60) / 1_000_000
            print(f"    ${cost:.4f}")
            content = result["choices"][0]["message"]["content"].strip()
            content = re.sub(r'^```json\s*', '', content)
            content = re.sub(r'\s*```$', '', content)
            batch_result = json.loads(content)
            new_trans.update(batch_result)
            print(f"    Got {len(batch_result)}")
        except Exception as e:
            print(f"    ERROR: {e}")

    # Merge
    merged = {**existing, **new_trans}
    print(f"\nTotal: {len(merged)} (was {len(existing)}, +{len(new_trans)} coaches)")

    # Write
    lines = [
        '/**',
        ' * World Cup player & coach name mapping: English → Chinese.',
        f' * {len(merged)} names covered.',
        ' * Auto-generated by scripts/translate_player_names.py',
        ' */',
        'const PLAYER_ZH = {',
    ]
    for key in sorted(merged.keys()):
        lines.append(f'  "{key}": "{merged[key]}",')
    lines += [
        '};', '',
        '/**',
        ' * Get Chinese name, falling back to original.',
        ' * @param {string} name',
        ' * @returns {string}',
        ' */',
        'export function playerNameZh(name) {',
        '  return PLAYER_ZH[name] || name;',
        '}', '',
    ]

    with open(js_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("Written!")

if __name__ == "__main__":
    main()
