#!/usr/bin/env python3
"""
批量翻译球员英文名 → 中文名
使用 GPT-4o-mini，分批处理，输出合并到 player-names-zh.js
"""

import json
import os
import re
import glob
import urllib.request
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
MODEL = "gpt-4o-mini"

def get_all_player_names():
    """Collect all player names from historical data."""
    names = set()

    # team-detail topPlayers
    for f in sorted(glob.glob(str(PROJECT / "public/data/team-detail/*.json"))):
        with open(f) as fh:
            data = json.load(fh)
        for p in data.get("topPlayers", []):
            n = p.get("name", "")
            if n: names.add(n)

    # wc-team-history goals
    hist_path = PROJECT / "public/data/wc-team-history.json"
    if hist_path.exists():
        with open(hist_path) as fh:
            hist = json.load(fh)
        for iso, td in hist.items():
            for t in td.get("tournaments", []):
                for g in t.get("goals", []):
                    n = g.get("player", "")
                    if n: names.add(n)

    # history/scorers.json
    scorers_path = PROJECT / "public/data/history/scorers.json"
    if scorers_path.exists():
        with open(scorers_path) as fh:
            sc = json.load(fh)
        for p in sc.get("allTime", []):
            n = p.get("player", "")
            if n: names.add(n)

    return sorted(names)


def get_existing_mapping():
    """Parse existing player-names-zh.js."""
    mapping = {}
    js_path = PROJECT / "lib/player-names-zh.js"
    with open(js_path) as fh:
        for line in fh:
            m = re.match(r'\s*"([^"]+)":\s*"([^"]+)"', line)
            if m:
                mapping[m.group(1)] = m.group(2)
    return mapping


def call_gpt_translate(names_batch):
    """Call GPT to translate a batch of player names."""
    names_text = "\n".join(names_batch)

    prompt = f"""你是一名资深足球翻译编辑。请将以下足球球员的英文名翻译为中文。

要求：
1. 使用中国体育媒体最常用的译名（如 Messi → 梅西，不是"梅希"）
2. 知名球员用公认的中文名
3. 不太知名的球员按音译
4. 阿拉伯/非洲/亚洲球员也要音译
5. 只输出 JSON 对象，key 是英文名，value 是中文名
6. 不要 markdown 代码块，不要其他文字

球员名单：
{names_text}"""

    payload = json.dumps({
        "model": MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 4000,
        "temperature": 0.1,
    })

    req = urllib.request.Request(
        "https://api.openai.com/v1/chat/completions",
        data=payload.encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {OPENAI_API_KEY}",
        },
    )

    with urllib.request.urlopen(req, timeout=60) as resp:
        result = json.loads(resp.read().decode("utf-8"))

    usage = result.get("usage", {})
    cost = (usage.get("prompt_tokens", 0) * 0.15 + usage.get("completion_tokens", 0) * 0.60) / 1_000_000
    print(f"    Tokens: {usage.get('prompt_tokens', 0)} in + {usage.get('completion_tokens', 0)} out = ${cost:.4f}")

    content = result["choices"][0]["message"]["content"].strip()
    content = re.sub(r'^```json\s*', '', content)
    content = re.sub(r'\s*```$', '', content)

    try:
        return json.loads(content)
    except json.JSONDecodeError as e:
        print(f"    [ERROR] JSON parse failed: {e}")
        print(f"    Response: {content[:300]}")
        return {}


def write_js_file(mapping):
    """Write the updated player-names-zh.js file."""
    js_path = PROJECT / "lib/player-names-zh.js"

    lines = [
        '/**',
        ' * World Cup player name mapping: English → Chinese.',
        f' * {len(mapping)} players covered (historical scorers + squad members).',
        ' * Auto-generated by scripts/translate_player_names.py',
        ' */',
        'const PLAYER_ZH = {',
    ]

    for key in sorted(mapping.keys()):
        val = mapping[key]
        lines.append(f'  "{key}": "{val}",')

    lines.append('};')
    lines.append('')
    lines.append('/**')
    lines.append(' * Get Chinese name for a player, falling back to original English name.')
    lines.append(' * @param {string} name - English player name')
    lines.append(' * @returns {string} Chinese name if known, otherwise original name')
    lines.append(' */')
    lines.append('export function playerNameZh(name) {')
    lines.append('  return PLAYER_ZH[name] || name;')
    lines.append('}')
    lines.append('')

    with open(js_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main():
    if not OPENAI_API_KEY:
        print("[ERROR] OPENAI_API_KEY not set")
        return

    print("=== Player Name Translator ===\n")

    # Step 1: Collect names
    print("[1/4] Collecting player names...")
    all_names = get_all_player_names()
    print(f"  Found {len(all_names)} unique names")

    # Step 2: Load existing
    print("[2/4] Loading existing translations...")
    existing = get_existing_mapping()
    print(f"  Existing: {len(existing)} translations")

    # Step 3: Find missing
    missing = [n for n in all_names if n not in existing]
    print(f"  Missing: {len(missing)} names to translate\n")

    if not missing:
        print("Nothing to translate!")
        return

    # Step 4: Translate in batches of 80
    print("[3/4] Translating with GPT...")
    BATCH_SIZE = 80
    new_translations = {}
    total_batches = (len(missing) + BATCH_SIZE - 1) // BATCH_SIZE

    for i in range(0, len(missing), BATCH_SIZE):
        batch = missing[i:i + BATCH_SIZE]
        batch_num = i // BATCH_SIZE + 1
        print(f"  Batch {batch_num}/{total_batches} ({len(batch)} names)...")

        try:
            result = call_gpt_translate(batch)
            new_translations.update(result)
            print(f"    Got {len(result)} translations")
        except Exception as e:
            print(f"    [ERROR] Batch failed: {e}")

    print(f"\n  Total new translations: {len(new_translations)}")

    # Step 5: Merge and write
    print("\n[4/4] Writing updated file...")
    merged = {**existing, **new_translations}
    write_js_file(merged)
    print(f"  Written {len(merged)} total translations to lib/player-names-zh.js")
    print("\n=== Done ===")


if __name__ == "__main__":
    main()
