export const wc2026Matches = [
  {
    id: "wc26-mex-rsa",
    stage: "A组",
    home: "墨西哥",
    away: "南非",
    score: "vs",
    kickoff: "2026-06-11",
    venue: "墨西哥城",
    status: "scheduled",
    meta: "揭幕战 · Estadio Azteca · 2026-06-11",
  },
  {
    id: "wc26-kor-uefa-a",
    stage: "A组",
    home: "韩国",
    away: "欧预附加赛A",
    score: "vs",
    kickoff: "2026-06-12",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "A组首轮 · 2026-06-12",
  },
  {
    id: "wc26-sui-qat",
    stage: "B组",
    home: "瑞士",
    away: "卡塔尔",
    score: "vs",
    kickoff: "2026-06-12",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "B组首轮 · 2026-06-12",
  },
  {
    id: "wc26-can-uefa-b",
    stage: "B组",
    home: "加拿大",
    away: "欧预附加赛B",
    score: "vs",
    kickoff: "2026-06-13",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "B组首轮 · 2026-06-13",
  },
  {
    id: "wc26-bra-hai",
    stage: "C组",
    home: "巴西",
    away: "海地",
    score: "vs",
    kickoff: "2026-06-13",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "C组首轮 · 2026-06-13",
  },
  {
    id: "wc26-usa-aus",
    stage: "D组",
    home: "美国",
    away: "澳大利亚",
    score: "vs",
    kickoff: "2026-06-13",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "D组首轮 · 2026-06-13",
  },
  {
    id: "wc26-sco-mar",
    stage: "C组",
    home: "苏格兰",
    away: "摩洛哥",
    score: "vs",
    kickoff: "2026-06-14",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "C组首轮 · 2026-06-14",
  },
  {
    id: "wc26-par-uefa-c",
    stage: "D组",
    home: "巴拉圭",
    away: "欧预附加赛C",
    score: "vs",
    kickoff: "2026-06-14",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "D组首轮 · 2026-06-14",
  },
  {
    id: "wc26-ger-ecu",
    stage: "E组",
    home: "德国",
    away: "厄瓜多尔",
    score: "vs",
    kickoff: "2026-06-14",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "E组首轮 · 2026-06-14",
  },
  {
    id: "wc26-civ-cur",
    stage: "E组",
    home: "科特迪瓦",
    away: "库拉索",
    score: "vs",
    kickoff: "2026-06-15",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "E组首轮 · 2026-06-15",
  },
  {
    id: "wc26-ned-uefa-d",
    stage: "F组",
    home: "荷兰",
    away: "欧预附加赛D",
    score: "vs",
    kickoff: "2026-06-15",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "F组首轮 · 2026-06-15",
  },
  {
    id: "wc26-tun-jpn",
    stage: "F组",
    home: "突尼斯",
    away: "日本",
    score: "vs",
    kickoff: "2026-06-16",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "F组首轮 · 2026-06-16",
  },
  {
    id: "wc26-bel-egy",
    stage: "G组",
    home: "比利时",
    away: "埃及",
    score: "vs",
    kickoff: "2026-06-16",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "G组首轮 · 2026-06-16",
  },
  {
    id: "wc26-nzl-irn",
    stage: "G组",
    home: "新西兰",
    away: "伊朗",
    score: "vs",
    kickoff: "2026-06-17",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "G组首轮 · 2026-06-17",
  },
  {
    id: "wc26-fra-sen",
    stage: "I组",
    home: "法国",
    away: "塞内加尔",
    score: "vs",
    kickoff: "2026-06-17",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "I组首轮 · 2026-06-17",
  },
  {
    id: "wc26-uru-sau",
    stage: "H组",
    home: "乌拉圭",
    away: "沙特阿拉伯",
    score: "vs",
    kickoff: "2026-06-17",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "H组首轮 · 2026-06-17",
  },
  {
    id: "wc26-spa-cpv",
    stage: "H组",
    home: "西班牙",
    away: "佛得角",
    score: "vs",
    kickoff: "2026-06-18",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "H组首轮 · 2026-06-18",
  },
  {
    id: "wc26-fpt2-nor",
    stage: "I组",
    home: "跨洲附加赛2",
    away: "挪威",
    score: "vs",
    kickoff: "2026-06-18",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "I组首轮 · 2026-06-18",
  },
  {
    id: "wc26-arg-aut",
    stage: "J组",
    home: "阿根廷",
    away: "奥地利",
    score: "vs",
    kickoff: "2026-06-18",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "J组首轮 · 2026-06-18",
  },
  {
    id: "wc26-alg-jor",
    stage: "J组",
    home: "阿尔及利亚",
    away: "约旦",
    score: "vs",
    kickoff: "2026-06-18",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "J组首轮 · 2026-06-18",
  },
  {
    id: "wc26-por-col",
    stage: "K组",
    home: "葡萄牙",
    away: "哥伦比亚",
    score: "vs",
    kickoff: "2026-06-19",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "K组首轮 · 2026-06-19",
  },
  {
    id: "wc26-uzb-fpt1",
    stage: "K组",
    home: "乌兹别克斯坦",
    away: "跨洲附加赛1",
    score: "vs",
    kickoff: "2026-06-19",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "K组首轮 · 2026-06-19",
  },
  {
    id: "wc26-eng-cro",
    stage: "L组",
    home: "英格兰",
    away: "克罗地亚",
    score: "vs",
    kickoff: "2026-06-19",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "L组首轮 · 2026-06-19",
  },
  {
    id: "wc26-gha-pan",
    stage: "L组",
    home: "加纳",
    away: "巴拿马",
    score: "vs",
    kickoff: "2026-06-19",
    venue: "FIFA 官方赛程场地",
    status: "scheduled",
    meta: "L组首轮 · 2026-06-19",
  },
  {
    id: "wc26-semi-1",
    stage: "半决赛",
    home: "待定",
    away: "待定",
    score: "vs",
    kickoff: "2026-07-14",
    venue: "达拉斯",
    status: "scheduled",
    meta: "半决赛 · 2026-07-14",
  },
  {
    id: "wc26-semi-2",
    stage: "半决赛",
    home: "待定",
    away: "待定",
    score: "vs",
    kickoff: "2026-07-15",
    venue: "亚特兰大",
    status: "scheduled",
    meta: "半决赛 · 2026-07-15",
  },
  {
    id: "wc26-final",
    stage: "决赛",
    home: "待定",
    away: "待定",
    score: "vs",
    kickoff: "2026-07-19",
    venue: "纽约新泽西",
    status: "scheduled",
    meta: "决赛 · New York New Jersey Stadium · 2026-07-19",
  },
];

const blankRow = (team) => ({
  team,
  played: 0,
  win: 0,
  draw: 0,
  loss: 0,
  points: 0,
});

export const wc2026Groups = {
  A: [blankRow("墨西哥"), blankRow("南非"), blankRow("韩国"), blankRow("欧预附加赛A")],
  B: [blankRow("加拿大"), blankRow("卡塔尔"), blankRow("瑞士"), blankRow("欧预附加赛B")],
  C: [blankRow("巴西"), blankRow("海地"), blankRow("苏格兰"), blankRow("摩洛哥")],
  D: [blankRow("美国"), blankRow("巴拉圭"), blankRow("澳大利亚"), blankRow("欧预附加赛C")],
  E: [blankRow("德国"), blankRow("科特迪瓦"), blankRow("厄瓜多尔"), blankRow("库拉索")],
  F: [blankRow("荷兰"), blankRow("突尼斯"), blankRow("日本"), blankRow("欧预附加赛D")],
  G: [blankRow("比利时"), blankRow("新西兰"), blankRow("埃及"), blankRow("伊朗")],
  H: [blankRow("乌拉圭"), blankRow("西班牙"), blankRow("佛得角"), blankRow("沙特阿拉伯")],
  I: [blankRow("法国"), blankRow("挪威"), blankRow("塞内加尔"), blankRow("跨洲附加赛2")],
  J: [blankRow("阿根廷"), blankRow("阿尔及利亚"), blankRow("奥地利"), blankRow("约旦")],
  K: [blankRow("葡萄牙"), blankRow("乌兹别克斯坦"), blankRow("哥伦比亚"), blankRow("跨洲附加赛1")],
  L: [blankRow("英格兰"), blankRow("加纳"), blankRow("巴拿马"), blankRow("克罗地亚")],
};

export const wc2026PollOptions = [
  { label: "巴西", votes: 31 },
  { label: "法国", votes: 26 },
  { label: "阿根廷", votes: 24 },
  { label: "西班牙", votes: 19 },
];

export const wc2026CountdownTarget = new Date("2026-06-11T20:00:00+09:00");
